### PR TITLE
Added type declarations

### PR DESCRIPTION
**Pull request by dburdan**
Just added a type declaration file for typescript users.

### CODE REVIEW

**Comment by kdex** [comment]
@dburdan Thank you for this, I appreciate it!

This may be surprising, but I'm relatively reluctant to accept this PR. While I'm pretty fond of static types, the type landscape is still quite a mess with ECMAScript.

First and foremost, TypeScript is not ECMAScript. It isn't even a superset of ECMAScript, despite Microsoft's claims. It's an entirely different language that somewhat resembles ECMAScript and implements sections of the ECMAScript standard that are explicitly prohibited from implementation (see, for instance, [`enum`, `interface`](https://esdiscuss.org/topic/removal-of-language-features#content-14)).

I've considered using [Flow](https://flow.org/), since specifying types out of band (as with this PR) leads to maintenance overhead and the potential to break as soon as the API changes. The reason I'm not using Flow is due to the high probability that the ECMAScript standard will end up with a different syntax, which would make `unzalgo` invalid ECMAScript that can only be read after transformation. There's also a very early proposal, [sirisian/ecmascript-types](https://github.com/sirisian/ecmascript-types), which adds optional type annotations to native ECMAScript, which would be the solution that I would prefer.

Realistically, as soon as that (or a similar) proposal gets to stage 4, TypeScript will fade away and meet with a similar fate as CoffeeScript did. Hence, I think it's probably the best to wait this out and see what syntax TC39 comes up with.

I hope you understand.

**Comment by ImRodry** [comment]
> @dburdan Thank you for this, I appreciate it!
> 
> This may be surprising, but I'm relatively reluctant to accept this PR. While I'm pretty fond of static types, the type landscape is still quite a mess with ECMAScript.
> 
> First and foremost, TypeScript is not ECMAScript. It isn't even a superset of ECMAScript, despite Microsoft's claims. It's an entirely different language that somewhat resembles ECMAScript and implements sections of the ECMAScript standard that are explicitly prohibited from implementation (see, for instance, [`enum`, `interface`](https://esdiscuss.org/topic/removal-of-language-features#content-14)).
> 
> I've considered using [Flow](https://flow.org/), since specifying types out of band (as with this PR) leads to maintenance overhead and the potential to break as soon as the API changes. The reason I'm not using Flow is due to the high probability that the ECMAScript standard will end up with a different syntax, which would make `unzalgo` invalid ECMAScript that can only be read after transformation. There's also a very early proposal, [sirisian/ecmascript-types](https://github.com/sirisian/ecmascript-types), which adds optional type annotations to native ECMAScript, which would be the solution that I would prefer.
> 
> Realistically, as soon as that (or a similar) proposal gets to stage 4, TypeScript will fade away and meet with a similar fate as CoffeeScript did. Hence, I think it's probably the best to wait this out and see what syntax TC39 comes up with.
> 
> I hope you understand.

So you're essentially saying fuck you to anyone who uses typescript and wants to use your module. Great, thanks!

**Comment by kdex** [comment]
@ImRodry

> So you're essentially saying fuck you to anyone who uses typescript and wants to use your module. Great, thanks!

First and foremost, there is no need for foul language here, so I'd appreciate it if we could keep this conversation civil.

I've expressed my concerns objectively, have taken the time to give a brief overview of what this means on a language level and have also addressed the implications for TypeScript. I think it would be great if you were to take similar care when composing your messages, as this is a purely technical discussion. Thank you.

**Comment by ImRodry** [comment]
> @ImRodry
> 
> > So you're essentially saying fuck you to anyone who uses typescript and wants to use your module. Great, thanks!
> 
> First and foremost, there is no need for foul language here, so I'd appreciate it if we could keep this conversation civil.
> 
> I've expressed my concerns objectively, have taken the time to give a brief overview of what this means on a language level and have also addressed the implications for TypeScript. I think it would be great if you were to take similar care when composing your messages, as this is a purely technical discussion. Thank you.

I think your opinion that TypeScript will eventually die is objectively wrong. You can see the usage of CoffeeScript and TypeScript over the time on this graph and TS is doing way better (despite the current, temporary, drop):
image
I don't understand why merging this would cause any issues because it doesn't change anything for JS users and it helps the life of TS users a lot, even if you decide not to use the language yourself. Please reconsider merging this pull request.

**Comment by kdex** [comment]
@ImRodry Thanks so much for getting back to me! I always appreciate a good discussion, as it helps me understand you, and it might also help you understand me a bit. I'd like to address your message bit by bit, if you don't mind:

> I think your opinion that TypeScript will eventually die is objectively wrong.

The reason why people are using TypeScript is for its static types, which I think are a great feature that I would love to use myself. The only thing I'm saying is: There are already proposals to add a static type system to ECMAScript in the works, and once that's standardized, the incentive for people to use ECMAScript derivatives, among which would be TypeScript, will inherently suffer.

When CoffeeScript came out in 2009, its syntactical conciseness was a game changer, so TC39 addressed that (albeit years later) via ECMAScript 2015 by adding a formal specification for arrow functions and similar features. That's the reason why in your image, the red graph flattens out over time. Conversely in TypeScript, static type checking was quite a game changer as well, so some people have adopted it, pressuring TC39 into addressing its benefits in later ECMAScript revisions. But that is also the reason why it is unavoidable that the blue graph in your image will follow a similar path over time. I'm aware it's been booming, but so have many other once popular things that are on their way into extinction. Like Facebook, for instance:

image

> (despite the current, temporary, drop)

There is no way for you (or me) to know if it's temporary–that's speculation.

> I don't understand why merging this would cause any issues because it doesn't change anything for JS users and it helps the life of TS users a lot, even if you decide not to use the language yourself. Please reconsider merging this pull request.

I'm aware that it makes things easier for some people, but it would make me happy if you could see how it makes things harder for my own maintenance as well. My point being that all of the sudden, I would now have to maintain type declarations and can't change the API anymore without also reflecting that in the type declarations. I can't test them either, because I don't use that language, so it'd be up to the community to keep the type declarations up to date, which would make it lag behind every time there's a new major version of this package. And *that* cost is just too high for me given that ECMAScript is already planning to specify types. Hope you can see where I'm coming from.

**Comment by ImRodry** [comment]
> The reason why people are using TypeScript is for its static types, which I think are a great feature that I would love to use myself. The only thing I'm saying is: There are already proposals to add a static type system to ECMAScript in the works, and once that's standardized, the incentive for people to use ECMAScript derivatives, among which would be TypeScript, will inherently suffer.

If that does happen then yeah, I agree that it will eventually die out but if it happens there will need to be a way to declare types and not even typescript can guess all the types by itself. So even if the system typescript uses is not used, it will definitely be something similar and you will sooner or later need to update to use this, even if TS dies.

> There is no way for you (or me) to know if it's temporary–that's speculation.

If you pay attention to the graph, there's a drop every year and it usually goes back to the same spot that it was at before, that's why I said it was temporary.

> I'm aware that it makes things easier for some people, but it would make me happy if you could see how it makes things harder for my own maintenance as well. My point being that all of the sudden, I would now have to maintain type declarations and can't change the API anymore without also reflecting that in the type declarations. I can't test them either, because I don't use that language, so it'd be up to the community to keep the type declarations up to date, which would make it lag behind every time there's a new major version of this package. And that cost is just too high for me given that ECMAScript is already planning to specify types. Hope you can see where I'm coming from.

Well even if you don't actively use typescript, you could make a test file where you use all of the functions provided by this package and check if the types are correct. Most of the time you just have to throw them in vscode and it will tell you if they're right or not. Not to mention this package is quite small and hasn't had that many updates (I don't mean this in a bad way, it does its job quite well) so I don't think it would be hard to keep that up to date. And another factor that makes this easier is that your types are all pretty easy to declare (string, boolean and array of numbers) which the author of this pull request has done quite well so again, I don't see a problem in adding this, even after the things you've discussed.

**Comment by ImRodry** [comment]
@kdex did you miss this?

**Pull request closed without merging**
